import 'package:drift/drift.dart';
import '../../../data/datasources/app_database.dart'; // This will be your main database class
import '../tables/episodes.dart';

part 'episodes_dao.g.dart'; // Generated by build_runner

@DriftAccessor(tables: [Episodes])
class EpisodesDao extends DatabaseAccessor<AppDatabase> with _$EpisodesDaoMixin {
  EpisodesDao(super.db);
}